# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Unit test confirmation of commit

on:
  push:
    branches: [ 3.0.0 ]
  pull_request:
    branches: [ 3.0.0 ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Redis Server
      # You may pin to the exact commit or the version.
      # uses: supercharge/redis-github-action@8dd3c86cd02fabe1bc459d55ba892a9ce91e23c6
      uses: supercharge/redis-github-action@1.1.0
      with:
        # Redis version to use
        redis-version: latest
    - name: Build with Maven
      run: mvn -B test --file pom.xml

#    - name: Upload Coverage Report to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: .*?/target/jacoco.exec$
#        flags: Unit tests
#        name: Jacoco-Converage-Report
#        fail_ci_if_error: true
#        verbose: true
